"""
Django settings for atonixcorp project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--&b$452=%e)ip6ud6w(y7sen-i(5su#6f9pingjymv6hf7i%e$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,atonixcorp.org,api.atonixcorp.org').split(',')

# Environment
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# Production domain settings
FRONTEND_DOMAIN = os.getenv('FRONTEND_DOMAIN', 'https://atonixcorp.org')
API_DOMAIN = os.getenv('API_DOMAIN', 'https://api.atonixcorp.org')


# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Zookeeper Configuration
ZOOKEEPER_HOSTS = os.getenv('ZOOKEEPER_HOSTS', 'localhost:2181')
ZOOKEEPER_ENABLED = os.getenv('ZOOKEEPER_ENABLED', 'false').lower() == 'true'

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092')
KAFKA_CLIENT_ID = os.getenv('KAFKA_CLIENT_ID', 'atonixcorp-django')
KAFKA_CONSUMER_GROUP_ID = os.getenv('KAFKA_CONSUMER_GROUP_ID', 'atonixcorp-consumers')
KAFKA_ENABLED = os.getenv('KAFKA_ENABLED', 'false').lower() == 'true'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '1025'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'false').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@atonixcorp.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '30'))

# Email template configuration
EMAIL_TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates', 'emails')
EMAIL_USE_LOCALTIME = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'drf_spectacular',  # API Documentation
    'security',  # Security module
    # 'observability',  # OpenTelemetry observability - Disabled for development
    'core',
    'projects',
    'teams',
    'focus_areas',
    'resources',
    'contact',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'observability.middleware.OpenTelemetryMiddleware',  # Disabled for development
    # 'observability.middleware.PerformanceMonitoringMiddleware',  # Disabled for development
    'security.middleware.SecurityMiddleware',  # Custom security middleware
    'security.middleware.IPWhitelistMiddleware',  # IP whitelist for admin
    'security.middleware.RequestValidationMiddleware',  # Request validation
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add Zookeeper middleware if enabled
if ZOOKEEPER_ENABLED:
    MIDDLEWARE.insert(-1, 'core.middleware.ZookeeperMiddleware')

# Add Kafka middleware if enabled
if KAFKA_ENABLED:
    MIDDLEWARE.insert(-1, 'core.kafka_middleware.KafkaMiddleware')

ROOT_URLCONF = 'atonixcorp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atonixcorp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for development, PostgreSQL for production
if ENVIRONMENT == 'production' and 'DATABASE_URL' in os.environ:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL'])
    }
else:
    # Development SQLite database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'security.authentication.JWTAuthentication',  # Secure JWT auth
        'security.api_keys.APIKeyAuthentication',  # API key auth
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'EXCEPTION_HANDLER': 'core.api_utils.custom_exception_handler',
}

# API Documentation with drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'AtonixCorp Platform API',
    'DESCRIPTION': '''
    Professional API for AtonixCorp Platform - A comprehensive project management and collaboration platform.
    
    ## Features
    - 🚀 **Project Management** - Create, manage, and track projects
    - 👥 **Team Collaboration** - Manage teams and team members
    - 🎯 **Focus Areas** - Organize work by focus areas
    - 📚 **Resource Management** - Manage and share resources
    - 📊 **Analytics Dashboard** - Comprehensive insights and metrics
    - 🔒 **Enterprise Security** - JWT authentication, API keys, rate limiting
    - ⚡ **High Performance** - Redis caching, optimized queries
    - 📡 **Real-time Features** - WebSocket support, live updates
    
    ## Authentication
    The API supports multiple authentication methods:
    - **JWT Tokens** - Bearer token authentication
    - **API Keys** - For service-to-service communication
    - **Session Authentication** - For web browser clients
    
    ## Rate Limiting
    - **Authenticated Users**: 1000 requests/hour
    - **Anonymous Users**: 100 requests/hour
    
    ## Support
    For technical support, contact: support@atonixcorp.com
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelRendering': 'example',
        'displayRequestDuration': True,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
    },
    'REDOC_DIST': 'SIDECAR',
    'SWAGGER_UI_DIST': 'SIDECAR',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'ENABLE_DJANGO_DEPLOY_CHECK': False,
    'DISABLE_ERRORS_AND_WARNINGS': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SCHEMA_PATH_PREFIX_TRIM': True,
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development Server'
        },
        {
            'url': 'https://api.atonixcorp.org',
            'description': 'Production Server'
        }
    ],
    'EXTERNAL_DOCS': {
        'description': 'AtonixCorp Platform Documentation',
        'url': 'https://docs.atonixcorp.org'
    },
    'CONTACT': {
        'name': 'AtonixCorp API Team',
        'email': 'api@atonixcorp.com',
        'url': 'https://atonixcorp.org/contact'
    },
    'LICENSE': {
        'name': 'Proprietary',
        'url': 'https://atonixcorp.org/license'
    },
}

# CORS settings for React frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://atonixcorp.org",
    "https://www.atonixcorp.org",
    "http://atonixcorp.org",  # Allow HTTP for development
    "http://www.atonixcorp.org",
]

# Additional CORS settings for production
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.atonixcorp\.org$",  # Allow subdomains
]

CORS_ALLOW_CREDENTIALS = True

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files configuration
STATIC_ROOT = BASE_DIR / 'staticfiles'

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# Environment variable helper
class Config:
    def __call__(self, key, default=None, cast=str):
        value = os.environ.get(key, default)
        if cast == bool:
            return str(value).lower() in ('true', '1', 'yes', 'on')
        elif cast == list and isinstance(value, str):
            return value.split(',') if value else []
        return cast(value) if value is not None else default
    
    def list(self, key, default=None):
        return self(key, default or [], cast=list)
    
    def bool(self, key, default=False):
        return self(key, default, cast=bool)

env = Config()

# Encryption settings
ENCRYPTION_KEY = env('ENCRYPTION_KEY', default=None)
JWT_SECRET_KEY = env('JWT_SECRET_KEY', default=SECRET_KEY)
JWT_ACCESS_TOKEN_LIFETIME = 900  # 15 minutes
JWT_REFRESH_TOKEN_LIFETIME = 604800  # 7 days
JWT_ISSUER = 'atonixcorp-platform'
API_KEY_SALT = env('API_KEY_SALT', default='default-salt')
AES_PASSWORD = env('AES_PASSWORD', default='default-aes-password')
AES_SALT = env('AES_SALT', default='default-salt').encode() if isinstance(env('AES_SALT', default='default-salt'), str) else env('AES_SALT', default=b'default-salt')

# Rate limiting settings
RATE_LIMIT_REQUESTS = int(env('RATE_LIMIT_REQUESTS', default=60))
RATE_LIMIT_WINDOW = int(env('RATE_LIMIT_WINDOW', default=60))
MAX_REQUEST_SIZE = 10 * 1024 * 1024  # 10MB

# Authentication settings
AUTH_MAX_ATTEMPTS = int(env('AUTH_MAX_ATTEMPTS', default=5))
AUTH_LOCKOUT_TIME = int(env('AUTH_LOCKOUT_TIME', default=900))

# Admin IP whitelist
ADMIN_WHITELIST_IPS = env.list('ADMIN_WHITELIST_IPS', default=[])

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
X_FRAME_OPTIONS = 'DENY'

# HTTPS settings
USE_HTTPS = env.bool('USE_HTTPS', default=ENVIRONMENT == 'production')
if USE_HTTPS:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Session security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hour

# CSRF protection
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_USE_SESSIONS = True

# Update CORS settings
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
cors_origins = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000', 
    'http://127.0.0.1:3000',
    'https://atonixcorp.org',
    'https://www.atonixcorp.org'
])
if cors_origins:
    CORS_ALLOWED_ORIGINS.extend(cors_origins)

# File upload security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Cache settings for security features
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,  # Use the same Redis URL from above
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Logging configuration for security events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 10*1024*1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Security referrer policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# =============================================================================
# OPENTELEMETRY CONFIGURATION
# =============================================================================

# OpenTelemetry settings
OTEL_ENABLED = env.bool('OTEL_ENABLED', default=False)  # Disable by default for development
OTEL_SERVICE_NAME = env('OTEL_SERVICE_NAME', default='atonixcorp-platform')
OTEL_SERVICE_VERSION = env('OTEL_SERVICE_VERSION', default='1.0.0')
OTEL_RESOURCE_ATTRIBUTES = env('OTEL_RESOURCE_ATTRIBUTES', default='')

# Tracing configuration
OTEL_ENABLE_CONSOLE = env.bool('OTEL_ENABLE_CONSOLE', default=False)  # Disable by default
OTEL_ENABLE_JAEGER = env.bool('OTEL_ENABLE_JAEGER', default=False)   # Disable by default
OTEL_ENABLE_OTLP = env.bool('OTEL_ENABLE_OTLP', default=False)
JAEGER_ENDPOINT = env('JAEGER_ENDPOINT', default='http://localhost:14268/api/traces')
JAEGER_AGENT_HOST = env('JAEGER_AGENT_HOST', default='localhost')
JAEGER_AGENT_PORT = int(env('JAEGER_AGENT_PORT', default=6831))

# Metrics configuration
OTEL_ENABLE_PROMETHEUS = env.bool('OTEL_ENABLE_PROMETHEUS', default=False)  # Disable by default
PROMETHEUS_METRICS_PORT = int(env('PROMETHEUS_METRICS_PORT', default=8001))

# OTLP configuration
OTEL_EXPORTER_OTLP_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT', default='http://localhost:4317')
OTEL_EXPORTER_OTLP_HEADERS = env('OTEL_EXPORTER_OTLP_HEADERS', default='')

# Sampling configuration
OTEL_TRACES_SAMPLER = env('OTEL_TRACES_SAMPLER', default='parentbased_traceidratio')
OTEL_TRACES_SAMPLER_ARG = float(env('OTEL_TRACES_SAMPLER_ARG', default=1.0))

# Initialize OpenTelemetry if enabled
# Disabled for development to avoid configuration issues
# if OTEL_ENABLED:
#     try:
#         from observability import initialize_opentelemetry
#         initialize_opentelemetry()
#     except Exception as e:
#         import logging
#         logger = logging.getLogger(__name__)
#         logger.warning(f'Failed to initialize OpenTelemetry: {e}')
#         # Continue without OpenTelemetry instead of failing
