version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: atonixcorp
      POSTGRES_USER: atonixcorp
      POSTGRES_PASSWORD: atonixpass
    ports:
      - "5433:5432"  # Different port to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Different port to avoid conflict
    volumes:
      - redis_data:/data

  app:
    image: atonixcorp-platform:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://atonixcorp:atonixpass@db:5432/atonixcorp
      - REDIS_URL=redis://redis:6379
      - DJANGO_SETTINGS_MODULE=atonixcorp.settings
      - DEBUG=True
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: