version: '3.8'

services:
  app:
    image: atonixcorp-platform:latest
    ports:
      - "8080:8080"
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=test-secret-key-for-testing-only
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3:rw
    depends_on:
      - redis
    networks:
      - atonix-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - atonix-network

networks:
  atonix-network:
    driver: bridge