apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: kube-system
spec:
  containers:
  - name: network-test
    image: nicolaka/netshoot
    command: ['sleep', '3600']
  restartPolicy: Never