apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-binding
  namespace: atonixcorp-platform
spec:
  containers:
  - name: test
    image: busybox
    command: ['sleep', '300']
    volumeMounts:
    - name: postgresql-data
      mountPath: /data
    - name: redis-data
      mountPath: /redis
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
      claimName: atonixcorp-platform-dev-postgresql-data
  - name: redis-data
    persistentVolumeClaim:
      claimName: atonixcorp-platform-dev-redis-data