# Gerrit CI/CD Configuration for AtonixCorp Platform
version: '3.8'

services:
  gerrit:
    image: gerritcodereview/gerrit:3.8
    ports:
      - "8081:8080"  # Gerrit web interface
      - "29418:29418"  # Gerrit SSH
    environment:
      - CANONICAL_WEB_URL=http://localhost:8081
      - GERRIT_INIT_ARGS=--install-all-plugins
    volumes:
      - gerrit_data:/var/gerrit
      - ./config/gerrit.config:/var/gerrit/etc/gerrit.config:ro
      - ./config/secure.config:/var/gerrit/etc/secure.config:ro
      - ./plugins:/var/gerrit/plugins:ro
    depends_on:
      - gerrit-db
    networks:
      - gerrit-network

  gerrit-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=gerrit
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=gerrit_pass
    volumes:
      - gerrit_db_data:/var/lib/postgresql/data
    networks:
      - gerrit-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"  # Jenkins web interface
      - "50000:50000"  # Jenkins agents
    environment:
      - JENKINS_OPTS=--httpPort=8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jobs:/var/jenkins_home/jobs:ro
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt:ro
    networks:
      - gerrit-network
    depends_on:
      - gerrit

  # Zuul for CI/CD pipeline orchestration
  zuul-scheduler:
    image: zuul/zuul-scheduler:latest
    ports:
      - "4730:4730"  # Gearman
    volumes:
      - ./zuul/main.yaml:/etc/zuul/main.yaml:ro
      - ./zuul/scheduler.yaml:/etc/zuul/scheduler.yaml:ro
      - zuul_scheduler_data:/var/lib/zuul
    networks:
      - gerrit-network
    depends_on:
      - gerrit
      - zookeeper

  zuul-web:
    image: zuul/zuul-web:latest
    ports:
      - "9000:9000"  # Zuul web interface
    volumes:
      - ./zuul/main.yaml:/etc/zuul/main.yaml:ro
      - ./zuul/web.yaml:/etc/zuul/web.yaml:ro
    networks:
      - gerrit-network
    depends_on:
      - zuul-scheduler

  zuul-executor:
    image: zuul/zuul-executor:latest
    privileged: true
    volumes:
      - ./zuul/main.yaml:/etc/zuul/main.yaml:ro
      - ./zuul/executor.yaml:/etc/zuul/executor.yaml:ro
      - zuul_executor_data:/var/lib/zuul
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gerrit-network
    depends_on:
      - zuul-scheduler

  # ZooKeeper for Zuul coordination
  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/logs
    networks:
      - gerrit-network

  # LDAP server for authentication (optional)
  ldap:
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=AtonixCorp
      - LDAP_DOMAIN=atonixcorp.com
      - LDAP_ADMIN_PASSWORD=admin_pass
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - gerrit-network

  # Nexus for artifact repository
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8083:8081"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=1024m
    volumes:
      - nexus_data:/nexus-data
    networks:
      - gerrit-network

networks:
  gerrit-network:
    driver: bridge

volumes:
  gerrit_data:
  gerrit_db_data:
  jenkins_data:
  zuul_scheduler_data:
  zuul_executor_data:
  zookeeper_data:
  zookeeper_logs:
  ldap_data:
  ldap_config:
  nexus_data: