apiVersion: v2
name: atonixcorp-platform
description: A Helm chart for AtonixCorp Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - atonixcorp
  - platform
  - django
  - react
  - postgresql
  - redis

home: https://atonixcorp.com
sources:
  - https://github.com/atonixcorp/platform

maintainers:
  - name: AtonixCorp DevOps Team
    email: devops@atonixcorp.com

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled