# Generated by Django 5.2.6 on 2025-09-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=128)),
                ('permissions', models.JSONField(default=list, help_text='List of allowed permissions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('rate_limit', models.PositiveIntegerField(default=1000, help_text='Requests per hour')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = any IP)')),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_api_keys',
                'indexes': [models.Index(fields=['key_hash'], name='security_ap_key_has_305507_idx'), models.Index(fields=['user', 'status'], name='security_ap_user_id_80d13f_idx'), models.Index(fields=['status', 'expires_at'], name='security_ap_status_463157_idx')],
            },
        ),
    ]
