---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.11-slim

inputs:
  - name: atonixcorp-source

run:
  path: bash
  args:
    - -c
    - |
      set -e
      
      echo "Running backend tests..."
      cd atonixcorp-source/backend
      
      # Set up test environment
      export DJANGO_SETTINGS_MODULE=atonixcorp.settings
      export DATABASE_URL=sqlite:///test_db.sqlite3
      export REDIS_URL=redis://localhost:6379/0
      export SECRET_KEY=test-secret-key
      export DEBUG=True
      export ENVIRONMENT=testing
      export OTEL_ENABLED=false
      
      # Install test dependencies
      pip install pytest pytest-django pytest-cov coverage
      
      # Run Django tests
      echo "Running Django unit tests..."
      python manage.py test --verbosity=2
      
      # Run pytest tests
      echo "Running pytest tests..."
      pytest -v --cov=. --cov-report=term-missing --cov-report=xml
      
      # Run security tests
      echo "Running security tests..."
      python -m pytest security/tests/ -v
      
      echo "Backend tests completed successfully"