---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: aquasec/trivy
    tag: latest

inputs:
  - name: atonixcorp-source

run:
  path: sh
  args:
    - -c
    - |
      set -e
      
      echo "Running comprehensive security scan..."
      cd atonixcorp-source
      
      # Create security reports directory
      mkdir -p security-reports
      
      # Install additional security tools
      apk add --no-cache python3 py3-pip nodejs npm
      pip3 install bandit safety semgrep
      
      # Backend security scan
      echo "Running backend security scan..."
      cd backend
      
      # Bandit security scan
      echo "Running Bandit..."
      bandit -r . -f json -o ../security-reports/bandit-report.json || true
      
      # Safety dependency check
      echo "Running Safety..."
      safety check --json --output ../security-reports/safety-report.json || true
      
      # Semgrep security patterns
      echo "Running Semgrep..."
      semgrep --config=auto --json --output=../security-reports/semgrep-report.json . || true
      
      cd ..
      
      # Frontend security scan
      echo "Running frontend security scan..."
      cd frontend
      npm audit --json > ../security-reports/npm-audit-report.json || true
      cd ..
      
      # Filesystem vulnerability scan
      echo "Running Trivy filesystem scan..."
      trivy fs --format json --output security-reports/trivy-fs-report.json . || true
      
      # Docker configuration scan
      echo "Scanning Dockerfile..."
      trivy config --format json --output security-reports/trivy-config-report.json . || true
      
      echo "Security scan completed. Check security-reports/ directory for detailed results."